spring:
  application:
    name: iunis-eats

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:54325/iuniseatsdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080




